version: '3.7'
services: 
  nginx:
    image: nginx:latest
    ports: 
    -  target: 80
       published: 80
       protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target:  /etc/nginx/nginx.conf
  sfia1-app:
    image: sfia1-app
    build: ./
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - PROJECT_DB_URI=${PROJECT_DB_URI}
    - SECRET_KEY=${SECRET_KEY} 




